import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'
import styles from '../styles/pageHeader.module.css'

const pageInfo = { 
  site_name:'fwywd-task-Lv3',
  type:'training_web_task_Lv1',
  url: 'https://ctinaito.github.io/fwywd-LP/',
  icon: './images/OGP_image.png'
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>
          {pageInfo.site_name}
        </title>
        <meta property="og:site_name" content={pageInfo.site_name}></meta>
        <meta property="og:type" content={pageInfo.type}></meta>
        <meta property="og:url" content={pageInfo.url}></meta>
        <meta property="icon" content={pageInfo.icon}></meta>
      </Head>
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-1">
        <div>
          <Image src="/logo.svg" alt="fwywd Logo" width={317} height={110} />
        </div>
        <div className="hidden md:grid grid-cols-6 gap-1">
          <div className="text-lg text-black-900">Home</div>
          <div className="text-lg text-black-900">起業家育成</div>
          <div className="text-lg text-black-900">コンセプト</div>
          <div className="text-lg text-black-900">採用</div>
          <div className="text-lg text-black-900">ニュース</div>
          <div className="text-lg text-black-900">運営会社</div>
        </div>
        <div>
          <a href="#_" className="inline-flex overflow-hidden text-white bg-gray-900 rounded group">
            <span className="px-3.5 py-2 text-white bg-main group-hover:bg-main flex items-center justify-center">
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M22.6894 12.1929C24.2134 12.9157 24.2134 15.0843 22.6894 15.8071L8.35677 22.6044C7.0298 23.2337 5.49976 22.2659 5.49976 20.7973L5.49976 7.20273C5.49976 5.7341 7.0298 4.76633 8.35677 5.39565L22.6894 12.1929Z" fill="#F2C94C"/>
              </svg>
            </span>
            <span className="bg-main pl-4 pr-5 py-2.5">無料説明会へ申し込み</span>
          </a>
        </div>
      </div>
    </div>
    /*
          <button className="bg-blue-200 hover:bg-blue-100 text-white rounded px-4 py-4">無料説明会へ申し込み</button>
        <div className="text-8xl text-purple-600">Hello!</div>
        <div className="hidden md:block text-8xl text-purple-400">Hello!</div>
        <div className="text-8xl text-purple-200">Hello!</div>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  */
  )
}
